### PR TITLE
Fix date when manually adding measurements

### LINKED ISSUE #165: When adding manual vital signs the dates appear incorrectly
### Description

When you go to add a manual vital measurement (HR, BP, Weight), the date that you choose on the "add data screen" (shown below in picture 1) does not match the date that is assigned when you save the vital measurement. The date that appears on the screen afterwards is always one day before the date that you initially assigned (seen below in the second picture)

Image1

Image2

### Reproduction

Add a manual vital measurement, select a date, click save, observe that the date that is saved is always one day before the date that you selected.

### Expected behavior

The date that is inputted in the manual vitals entry should match the date that appears on the saved data. 

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by eldcn**
# *Fix date when manually adding measurements*

## :recycle: Current situation & Problem
- Fixes #165 
- Use `java.time.Instant` for time picker state to properly include time zone information when formatting
- Adapt all three view models to use the same time picker state mapper instead of separate ui state mappers
- Adapt and extend unit tests

## :gear: Release Notes 
*Add a bullet point list summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*
*Include code snippets that provide examples of the feature implemented or links to the documentation if it appends or changes the public interface.*

## :books: Documentation
*Please ensure that you properly document any additions in conformance to [Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md).*
*You can use this section to describe your solution, but we encourage contributors to document your reasoning and changes using in-line documentation.* 

## :white_check_mark: Testing
*Please ensure that the PR meets the testing requirements set by CodeCov and that new functionality is appropriately tested.*
*This section describes important information about the tests and why some elements might not be testable.*

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [ ] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by Basler182 — APPROVED** [review]
LGTM! 🚀 Great work on fixing the timezone issue and unifying the time picker state.

File: app/src/main/kotlin/edu/stanford/bdh/engagehf/health/bloodpressure/bottomsheet/TimePickerStateMapper.kt [hunk 1]
```diff
@@ -0,0 +1,54 @@
+package edu.stanford.bdh.engagehf.health.bloodpressure.bottomsheet
```
Comment (pauljohanneskraft) [inline app/src/main/kotlin/edu/stanford/bdh/engagehf/health/bloodpressure/bottomsheet/TimePickerStateMapper.kt:1]: I think this would make more sense in the `components` folder, right? Rather than being scoped to blood pressure

File: app/src/main/kotlin/edu/stanford/bdh/engagehf/health/bloodpressure/bottomsheet/TimePickerStateMapper.kt [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+    private val dateFormatter: DateFormatter,
+    private val timeProvider: TimeProvider,
+) {
+
+    fun mapNow(): TimePickerState {
+        val now = timeProvider.nowInstant()
+        val localTime = timeProvider.nowLocalTime()
+        return TimePickerState(
+            selectedDate = now,
+            selectedTime = localTime,
```
Comment (pauljohanneskraft) [inline app/src/main/kotlin/edu/stanford/bdh/engagehf/health/bloodpressure/bottomsheet/TimePickerStateMapper.kt:22]: Instant already has the time, right? Why do we have time and date separate then?

**Review by pauljohanneskraft — APPROVED** [review]
Looks good to me, but I haven't tested it. I have some smaller remarks, let me know, if there are any questions.

File: app/src/main/kotlin/edu/stanford/bdh/engagehf/health/bloodpressure/bottomsheet/TimePickerStateMapper.kt (hunk 2 above)
Comment (eldcn) [reply app/src/main/kotlin/edu/stanford/bdh/engagehf/health/bloodpressure/bottomsheet/TimePickerStateMapper.kt]: We create the time from two ui components, a date picker which sends utc millis at the start of the day, and a time picker which returns the hour and minutes. Then we build the ultimative timestamp from the date of the instant and the hour and minutes of the local time

File: app/src/main/kotlin/edu/stanford/bdh/engagehf/health/bloodpressure/bottomsheet/TimePickerStateMapper.kt (hunk 1 above)
Comment (eldcn) [reply app/src/main/kotlin/edu/stanford/bdh/engagehf/health/bloodpressure/bottomsheet/TimePickerStateMapper.kt]: valid point, components is intended to contain composables, I moved it under a new `time` package

File: app/src/main/kotlin/edu/stanford/bdh/engagehf/health/time/TimePickerStateMapper.kt [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+    fun mapDate(
+        date: Instant,
+        timePickerState: TimePickerState,
+    ) = timePickerState.copy(
+        selectedDate = date,
+        selectedDateFormatted = format(date)
+    )
+
+    fun mapInstant(timePickerState: TimePickerState): Instant = with(timePickerState) {
+        val zoneId = ZoneId.systemDefault()
```
[the remark this answers is not in the document]
Comment (Basler182) [reply app/src/main/kotlin/edu/stanford/bdh/engagehf/health/time/TimePickerStateMapper.kt:47]: From Android Doc: 

```kotlin
/**
     * A timestamp that represents the selected date _start_ of the day in _UTC_ milliseconds
     * from the epoch.
     *
     * @throws IllegalArgumentException in case the value is set with a timestamp that does not fall
     * within the [yearRange].
     */
```

Because California is UTC-8, and the UTC time is taken at the start of the day, it is always the day before. In Germany, for example, where we have UTC+2, it is always the same day and therefore it was never a problem for either of us during testing.

[the remark this answers is not in the document]
Comment (eldcn) [reply app/src/main/kotlin/edu/stanford/bdh/engagehf/health/time/TimePickerStateMapper.kt]: You are right, I managed to reproduce the issue in a unit test. Fixed in this commit: https://github.com/StanfordSpezi/SpeziKt/pull/170/commits/79f8ecd8fec6dc62af0f7bc25062e67225967828

Using system default zone id, the unit test would fail:

```
expected: 2025-01-15T04:12:00Z
but was : 2025-01-16T03:12:00Z
```

Thanks 🚀

**Comment by PSchmiedmayer** [comment]
Thank you @eldcn and thank you for the reviews @pauljohanneskraft & @Basler182!
