### PR TITLE
Fix message dismissing and extract message handling from home view model

### LINKED ISSUE #101: Refactor Bluetooth ViewModel and HomeScreen logic
### Problem

The `BluetoothViewModel` currently handles a lot more than it should and is tightly coupled with the Home Screen logic.

### Solution

- Create a new component named `MessageHandler` and extract the message logic currently residing in `BluetoothViewModel` into this component.
- Inject the `MessageHandler` into `MainActivityViewModel` and invoke a new action that will internally call the handler.
- Rename `BluetoothViewModel` to `HomeScreenViewModel` to better reflect its purpose.
- Extract Bluetooth-related logic into its own service to promote separation of concerns and improve maintainability.

### Additional context

This refactor will simplify the ViewModel, improve the separation of concerns, and make the application easier to test and extend in the future.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### LINKED ISSUE #153: Messages Are Not Dismissible & Don't Get Dismissed Automatically
### Description

Messages are currently not dismissed & uploading measurements does not show the messages being dismissed.

### Reproduction

- [ ] Interact with a message (e.g. the welcome video) and the message is not dismissed.
- [ ] Do a blood pressure measurement & weight scale measurement, the messages are not automatically dismissed

### Expected behavior

Messages should be dismissed.

### Additional context

it seems like it is not longer possible to set the completionDate of the message and one has to use a firebaseFunction instead ([for reference](https://github.com/StanfordBDHG/ENGAGE-HF-Firebase?tab=readme-ov-file#dismissmessage)). the code would need to be changed to something like:
```
firebaseFunctions.getHttpsCallable("dismissMessage")
    .call(
          mapOf(
            "userId" to uid,
            "messageId" to messageId,
            )
        ).await()
```
from previous:
```
firestore.collection("users")
    .document(uid)
    .collection("messages")
    .document(messageId)
    .update("completionDate", ZonedDateTime.now())
```
implementation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by eldcn**
# *Message completion*

## :recycle: Current situation & Problem
- Fixes #101 by extracting message handling logic out of home view model and reuse in main activity during push notifications flow
- Fixes #153 by using `dismissMessage` firebase function instead of updating `completionDate` field. Messages are dismissed correctly now, and we receive a new update (within a couple of seconds) upon dismissal via the snapshot listener
- Adapt and extend unit tests

## :gear: Release Notes 
*Add a bullet point list summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*
*Include code snippets that provide examples of the feature implemented or links to the documentation if it appends or changes the public interface.*

## :books: Documentation
*Please ensure that you properly document any additions in conformance to [Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md).*
*You can use this section to describe your solution, but we encourage contributors to document your reasoning and changes using in-line documentation.* 

## :white_check_mark: Testing
*Please ensure that the PR meets the testing requirements set by CodeCov and that new functionality is appropriately tested.*
*This section describes important information about the tests and why some elements might not be testable.*

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [ ] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/kotlin/edu/stanford/bdh/engagehf/messages/MessageRepository.kt [hunk 1]
```diff
@@ -50,19 +55,23 @@ internal class MessageRepository @Inject constructor(
...
+                    "userId" to uid,
+                    "messageId" to messageId,
+                )
+                firebaseFunctions.getHttpsCallable("dismissMessage")
+                    .call(params)
+                    .await()
+
+                logger.i { "Message completion for $messageId finished successfully" }
+            }.onFailure {
+                logger.e(it) { "Error while completing message" }
```
Comment (Basler182) [inline app/src/main/kotlin/edu/stanford/bdh/engagehf/messages/MessageRepository.kt:73]:
```suggestion
                logger.e(it) { "Error while completing message with id $messageId" }
```

**Review by Basler182 — APPROVED** [review]
Logic refactoring, dismissMessage fix and tests have been implemented great 🚀
