### PR TITLE
Task/issue 165

### LINKED ISSUE #165: When adding manual vital signs the dates appear incorrectly
### Description

When you go to add a manual vital measurement (HR, BP, Weight), the date that you choose on the "add data screen" (shown below in picture 1) does not match the date that is assigned when you save the vital measurement. The date that appears on the screen afterwards is always one day before the date that you initially assigned (seen below in the second picture)

Image1

Image2

### Reproduction

Add a manual vital measurement, select a date, click save, observe that the date that is saved is always one day before the date that you selected.

### Expected behavior

The date that is inputted in the manual vitals entry should match the date that appears on the saved data. 

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by eldcn**
# *Date mapping when manually adding measurements*

## :recycle: Current situation & Problem
- Fixes #165 
- Correction from previous PR: Initial time (now) is being mapped correctly in default zone id, however when receiving a new selected date instant from the date picker, it should be formatted in UTC to reflect the same value as in the picker
- Further adapt the unit tests

## :gear: Release Notes 
*Add a bullet point list summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*
*Include code snippets that provide examples of the feature implemented or links to the documentation if it appends or changes the public interface.*

## :books: Documentation
*Please ensure that you properly document any additions in conformance to [Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md).*
*You can use this section to describe your solution, but we encourage contributors to document your reasoning and changes using in-line documentation.* 

## :white_check_mark: Testing
*Please ensure that the PR meets the testing requirements set by CodeCov and that new functionality is appropriately tested.*
*This section describes important information about the tests and why some elements might not be testable.*

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [ ] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by PSchmiedmayer — APPROVED** [review]
Date and times can be complicated! Thank you for further driving into this @eldcn! 🚀

File: app/src/main/kotlin/edu/stanford/bdh/engagehf/health/time/TimePickerStateMapper.kt [hunk 1]
```diff
@@ -40,15 +40,18 @@ class TimePickerStateMapper @Inject constructor(
...
         selectedDate = date,
-        selectedDateFormatted = format(date)
+        selectedDateFormatted = dateFormatter.formatUTC(date, DATE_FORMAT)
     )
 
     fun mapInstant(timePickerState: TimePickerState): Instant = with(timePickerState) {
-        val zoneId = ZoneId.of("UTC")
-        val date = selectedDate.atZone(zoneId).toLocalDate()
-        return LocalDateTime.of(date, selectedTime).atZone(zoneId).toInstant()
+        val date = selectedDate.atZone(UTC_ZONE_ID).toLocalDate()
```
Comment (Basler182) [inline app/src/main/kotlin/edu/stanford/bdh/engagehf/health/time/TimePickerStateMapper.kt:47]: Minor: Perhaps it would be useful to rename `selectedDate` to `selectedInstant` after all the changes to better reflect the actual type. This would make this line, for example, even easier to understand.

**Review by Basler182 — APPROVED** [review]
Good job 🚀
