### PR TITLE
fix #90 don't dismiss failed message action

### LINKED ISSUE #90: Message Action Complete Handling
### Problem

At present, the message action is not based on whether it was successful, but always completed

### Solution

It should be checked whether the action is successful and only then should the message be completed.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by Basler182**
# *don't dismiss failed message action*

## :recycle: Current situation & Problem
#90 

## :gear: Release Notes 
- don't dismiss failed message action

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/kotlin/edu/stanford/bdh/engagehf/bluetooth/BluetoothViewModel.kt [hunk 1]
```diff
@@ -220,7 +224,15 @@ class BluetoothViewModel @Inject internal constructor(
     ) {
         when (messagesAction) {
             is MessagesAction.HealthSummaryAction -> {
-                handleHealthSummaryAction(messageId)
+                handleHealthSummaryAction(messageId).onFailure {
+                    return // on failure, we don't want to dismiss the message
```
Comment (eldcn) [inline app/src/main/kotlin/edu/stanford/bdh/engagehf/bluetooth/BluetoothViewModel.kt:228]: very minor as I tend to avoid comments and want the code to speak instead 😅 . Before when I would create a `var shouldDismissMessage = isDismissable` and in both failures here force set it to false `shouldDismissMessage = false`

File: app/src/main/kotlin/edu/stanford/bdh/engagehf/bluetooth/BluetoothViewModel.kt [hunk 2]
```diff
@@ -242,32 +254,27 @@ class BluetoothViewModel @Inject internal constructor(
...
-        ).getOrNull()?.let { video ->
-            navigator.navigateTo(
-                EducationNavigationEvent.VideoSectionClicked(
-                    video = video
-                )
+        ).onSuccess { video ->
+            navigator.navigateTo(EducationNavigationEvent.VideoSectionClicked(video))
+        }.onFailure {
+            messageNotifier.notify(
+                message = "Error while handling message action."
```
Comment (eldcn) [inline app/src/main/kotlin/edu/stanford/bdh/engagehf/bluetooth/BluetoothViewModel.kt:271]: Can we extract to string resources? Message notifier supports notify(resId) already

File: modules/education/src/main/java/edu/stanford/spezi/modules/education/videos/EducationViewModel.kt [hunk 3]
```diff
@@ -27,11 +29,11 @@ internal class EducationViewModel @Inject constructor(
...
         viewModelScope.launch {
             _uiState.value = UiState.Loading
-            val result = educationRepository.getVideoSections()
-            _uiState.value = if (result.isSuccess) {
-                UiState.Success(EducationUiState(videoSections = result.getOrNull() ?: emptyList()))
-            } else {
-                UiState.Error("Failed to load video sections")
+            educationRepository.getVideoSections().onFailure {
+                logger.e(it) { "Failed to load video sections" }
+                _uiState.value = UiState.Error("Failed to load video sections")
```
Comment (eldcn) [inline modules/education/src/main/java/edu/stanford/spezi/modules/education/videos/EducationViewModel.kt:34]: also here, extracting the string to string resources and updating the error message type to a `StringResource` would be great

File: app/src/main/kotlin/edu/stanford/bdh/engagehf/bluetooth/BluetoothViewModel.kt [hunk 4]
```diff
@@ -218,9 +223,20 @@ class BluetoothViewModel @Inject internal constructor(
         messageId: String,
         isDismissible: Boolean,
     ) {
+        var shouldDismissMessage = isDismissible
         when (messagesAction) {
             is MessagesAction.HealthSummaryAction -> {
-                handleHealthSummaryAction(messageId)
+                handleHealthSummaryAction(messageId).onFailure {
+                    shouldDismissMessage = false
+                    return
```
Comment (eldcn) [inline app/src/main/kotlin/edu/stanford/bdh/engagehf/bluetooth/BluetoothViewModel.kt:231]: return is also not needed anymore imo, either return only + comment as it was before or address via the new `shouldDismissMessage` variable which will skip dismissing below

Comment (Basler182) [reply app/src/main/kotlin/edu/stanford/bdh/engagehf/bluetooth/BluetoothViewModel.kt]: i left the `return` in because i thought it would make it easier to read, that nothing more would happen in this case, but i removed it now
